### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suamirochadev**
Add Ethical Hacker Certificate.

### CODE REVIEW

**Comment by dragonsea0927** [comment]
Hello.

**Review by dragonsea0927 — APPROVED** [review]

**Comment by dragonsea0927** [comment]
Please explain how to update PR.

**Comment by suamirochadev** [comment]
Updated

**Review by dragonsea0927 — APPROVED** [review]

**Review by dragonsea0927 — APPROVED** [review]

**Comment by dragonsea0927** [comment]
Thanks

**Review by dragonsea0927 — APPROVED** [review]

**Pull request merged**
