### PR TITLE
Add Boomi certifications

### PR DESCRIPTION
**Pull request by stn1slv**
Adding free certifications from Boomi:

- Professional API Management Certification 2022	[Link](https://train.boomi.com/courses/505f285a-b319-4d8c-bfb5-edb9388718b4)
- Professional API Design Certification 2022	[Link](https://train.boomi.com/courses/4ff9ce74-b59b-46e8-8f5a-1bbf47a9646e)
- Associate Developer Certification 2022	[Link](https://train.boomi.com/courses/7a16bffb-44eb-494d-910e-da9c9c73eb24)
- Associate EDI for X12 Certification 2022	[Link](https://train.boomi.com/courses/1292458c-1cb8-4c70-89b3-a5511a93e0f0)
- Associate Flow Essentials Certification 2022	[Link](https://train.boomi.com/courses/21ef4c54-2be2-47fe-b15a-a37d933dfa49)
- Associate Master Data Hub Certification 2022	[Link](https://train.boomi.com/courses/f598855d-b139-4dff-8179-c5aaeb2ba7a1)
- Development and Application Architecture Certification 2022	[Link](https://train.boomi.com/courses/5dddea89-e441-4491-9efe-213e3c024d46)
- Professional Developer Certification 2022	[Link](https://train.boomi.com/courses/456252e5-315c-4269-a23c-88f7409a07ac)
- Professional Flow Developer Certification 2022	[Link](https://train.boomi.com/courses/cbd792ee-c609-4a1f-a2f8-51ab97db4be7)
- Associate Administrator Certification 2022	[Link](https://train.boomi.com/courses/12caf173-54f8-4550-8bf9-120753b2157e)
- Professional Linux Operational Administrator Certification 2022	[Link](https://train.boomi.com/courses/43b35109-6218-486d-83b1-d2b43362db51)
- Professional Windows Operational Administrator Certification 2022	[Link](https://train.boomi.com/courses/a43bbb4d-9747-404c-93ba-e696447e3189)

### CODE REVIEW

**Comment by stn1slv** [comment]
@karentamrazyan could you please review this pull request?

**Comment by karentamrazyan** [comment]
hi @stn1slv . Thanks for your contribution, but all those suggested courses / certifications are behind a registration wall. Hence, we cannot neither check nor accept them.

**Comment by stn1slv** [comment]
@karentamrazyan, there is a confirmation from the vendor that all certifications are free.
Please see details by the link: 
https://resources.boomi.com/resources/blog-posts/get-trained-and-certified-on-the-boomi-platform-anytime-anywhere-—-for-free

If you accept them, I'll submit a new PR for them.

**Comment by karentamrazyan** [comment]
ok, great. Please submit a new PR.

**Comment by stn1slv** [comment]
Please see in PR #95

**Pull request closed without merging**
