### PR TITLE
Added NewRelic Certification

### PR DESCRIPTION
**Pull request by bpdesilva**
NewRelic Programmability Certification

### CODE REVIEW

**Comment by bpdesilva** [comment]
@karentamrazyan made a small update would help the community.

**Comment by Sujalgu** [comment]
Certification is in which course

**Comment by bpdesilva** [comment]
https://learn.newrelic.com/programmability-certification @Sujalgu  Please refer link

**Comment by karentamrazyan** [comment]
thanks @bpdesilva !

**Pull request merged**
